// Generated by android/tools/generate_catalog.py.
package local.pianopracticeplanner.i18n

internal object Catalogs {
    fun get(language: String): Map<String, String> = when(language) {
        "ja" -> catalogja
        "en" -> catalogen
        "zh-Hans" -> catalogzhHans
        "zh-Hant" -> catalogzhHant
        "ko" -> catalogko
        "es" -> cataloges
        "fr" -> catalogfr
        "de" -> catalogde
        "pt" -> catalogpt
        else -> catalogen
    }
}
