#!/usr/bin/env python3
"""Validate offline translations and generate pure Kotlin catalogs. Run with --check in CI."""
import argparse
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
LOCALES = ('ja', 'en', 'zh-Hans', 'zh-Hant', 'ko', 'es', 'fr', 'de', 'pt')
OUT = ROOT / 'app/src/main/java/local/pianopracticeplanner/i18n'

def literal(value):
    return json.dumps(value, ensure_ascii=False).replace('$', '\\$')

def generate(check=False):
    base = json.loads((ROOT / 'translations/ja.json').read_text(encoding="utf-8"))
    files = {}
    for locale in LOCALES:
        values = json.loads((ROOT / f'translations/{locale}.json').read_text(encoding="utf-8"))
        assert values.keys() == base.keys(), f'{locale}: missing or extra keys'
        for key, value in values.items():
            assert value.strip(), f'{locale}/{key}: empty translation'
            assert sorted(re.findall(r'\{\d+\}', value)) == sorted(re.findall(r'\{\d+\}', base[key])), f'{locale}/{key}: placeholders differ'
        name = locale.replace('-', '')
        files[f'Catalog{name}.kt'] = ('// Generated by android/tools/generate_catalog.py; edit translations/*.json.\n'
            'package local.pianopracticeplanner.i18n\n\n'
            f'internal val catalog{name}: Map<String, String> by lazy {{ mapOf(\n' +
            ',\n'.join(f'    {literal(key)} to {literal(value)}' for key, value in values.items()) + '\n) }\n')
    files['Catalogs.kt'] = ('// Generated by android/tools/generate_catalog.py.\npackage local.pianopracticeplanner.i18n\n\n'
        'internal object Catalogs {\n    fun get(language: String): Map<String, String> = when(language) {\n' +
        ''.join(f'        "{locale}" -> catalog{locale.replace("-", "")}\n' for locale in LOCALES) +
        '        else -> catalogen\n    }\n}\n')
    for name, content in files.items():
        path = OUT / name
        if check:
            assert path.read_text(encoding="utf-8") == content, f'{name} is stale; run generator'
        else:
            path.write_text(content, encoding="utf-8")
    print(f'Validated {len(base)} messages in {len(LOCALES)} locales.')

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    generate(parser.parse_args().check)
